# Generated by Django 5.1.1 on 2024-10-16 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='completed_at',
            new_name='completed',
        ),
    ]
